Changed message around absent results

diff --git a/bin/verify-pre-deployment-build b/bin/verify-pre-deployment-build
--- a/bin/verify-pre-deployment-build
+++ b/bin/verify-pre-deployment-build
@@ -8,45 +8,48 @@ jx step stash --pattern="target/site/*" --to-path=${REPO_NAME}/${BUILD_NAME} -c 
 if ls target/surefire-reports/*.xml>/dev/null 2>&1; then
   if grep -rnw target/surefire-reports/*.xml -e "<failure" >/dev/null 2>&1 || grep -rnw target/surefire-reports/*.xml -e "<error" >/dev/null 2>&1; then
     echo >&2 "Pre-deployment tests failed for ${REPO_NAME}-${BUILD_NAME}."
-    FAILED_CHECKS="Pre-deployment tests; "
+    FAILED_CHECKS="Pre-deployment tests\n"
     publish-status "Pre-deployment tests" "failure" "surefire-report.html"
   else
     publish-status "Pre-deployment tests" "success" "surefire-report.html"
   fi
 else
   echo >&2 "No pre-deployment test results found for ${REPO_NAME}-${BUILD_NAME}."
-  FAILED_CHECKS="Pre-deployment tests; "
-  publish-status "Pre-deployment tests" "failure" "surefire-report.html"
+  FAILED_CHECK="No pre-deployment test results produced by build"
+  FAILED_CHECKS="${FAILED_CHECKS}${FAIlED_CHECK}\n"
+  publish-status "Pre-deployment tests" "pending" "surefire-report.html" "${FAILED_CHECK}"
 fi
 if [[ -f target/checkstyle-result.xml ]]; then
   if grep -rnw target/checkstyle-result.xml -e "<error" >/dev/null 2>&1; then
     echo >&2 "Checkstyle rules were violated for ${REPO_NAME}-${BUILD_NAME}."
-    FAILED_CHECKS="${FAILED_CHECKS}Checkstyle; "
+    FAILED_CHECKS="${FAILED_CHECKS}Checkstyle\n"
     publish-status "Checkstyle" "failure" "checkstyle.html"
   else
     publish-status "Checkstyle" "success" "checkstyle.html"
   fi
 elif [ "${SKIP_CHECKSTYLE}" != "true" ]; then
   echo >&2 "No checkstyle results found for ${REPO_NAME}-${BUILD_NAME}."
-  FAILED_CHECKS="${FAILED_CHECKS}Checkstyle; "
-  publish-status "Checkstyle" "failure" "checkstyle.html"
+  FAILED_CHECK="No checkstyle results produced by build"
+  FAILED_CHECKS="${FAILED_CHECKS}${FAIlED_CHECK}\n"
+  publish-status "Checkstyle" "pending" "checkstyle.html" "${FAILED_CHECK}"
 fi
 if [[ -f target/site/dependency-check-junit.xml ]]; then
   if grep -rnw target/site/dependency-check-junit.xml -e "<failure" >/dev/null 2>&1; then
     echo >&2 "OWASP has found dependencies with vulnerabilities for ${REPO_NAME}-${BUILD_NAME}."
-    FAILED_CHECKS="${FAILED_CHECKS}OWASP Maven Dependency Check; "
+    FAILED_CHECKS="${FAILED_CHECKS}OWASP Maven Dependency Check\n"
     publish-status "OWASP CVE" "failure" "dependency-check-report.html"
   else
     publish-status "OWASP CVE" "success" "dependency-check-report.html"
   fi
 else
   echo >&2 "OWASP has found dependencies with vulnerabilities for ${REPO_NAME}-${BUILD_NAME}."
-  FAILED_CHECKS="${FAILED_CHECKS}OWASP Maven Dependency Check; "
-  publish-status "OWASP CVE" "failure" "dependency-check-report.html"
+  FAILED_CHECK="No OWASP dependency check results produced by build"
+  FAILED_CHECKS="${FAILED_CHECKS}${FAIlED_CHECK}\n"
+  publish-status "OWASP CVE" "pending" "dependency-check-report.html" "${FAIlED_CHECK}"
 fi
 if [ -z "${FAILED_CHECKS}" ]; then
   echo "Congratulations! No build failures found for ${REPO_NAME}-${BUILD_NAME}."
 else
-  echo >&2 "The following checks failed: for ${REPO_NAME}-${BUILD_NAME} : ${FAILED_CHECKS}"
+  printf >&2 "The following checks failed for ${REPO_NAME}-${BUILD_NAME}:\n${FAILED_CHECKS}"
   exit 1
 fi
